import Head from 'next/head'
import Image from 'next/image'
import Header from '../Components/Header'
import {getSession} from 'next-auth/client'
import Login from '../Components/Login'
import Sidebar from '../Components/Sidebar'
import Feed from '../Components/Feed'
import Widgets from '../Components/Widgets'

export default function Home({session}) {
  if(!session) return <Login/>
  return (
    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>Facebook</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <Header/>

      <main className="flex">
        {/* Sidebar */}
        <Sidebar/>
        {/* Feed */}
        <Feed/>
        {/* Widget */}

        <div>
          <Widgets />
          </div>
      </main>

     
    </div>
  )
}


export async function getServerSideProps(context) {
const session=await getSession(context)


return{
  props: {
    session,
    
  }
}
}

